# Generated by Django 4.1.3 on 2022-12-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data_text',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
