# Generated by Django 4.1.3 on 2022-12-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_book_resenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_text',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='data'),
        ),
    ]
